Feature2019/12/14 create login screen
tanakafumiaki/task-collection pull request #11
Opened 2019-12-15 13:23 UTC by tanakafumiaki

ログイン画面を作成しました。

2019-12-15 14:08 UTC, tsurutan commented
@tanakafumiaki 
こちらログイン画面のスクショも一緒に乗せてもらえると助かります！

2019-12-15 14:39 UTC, tanakafumiaki commented
<img width="1440" alt="スクリーンショット 2019-12-15 23 34 56" src="https://user-images.githubusercontent.com/38996387/70864315-2edbd080-1f94-11ea-94da-f4d93d5d088a.png">

2019-12-15 14:41 UTC, tanakafumiaki commented
スクリーンショットをアップロードしました。
よろしくお願いいたします。

2019-12-15 14:52 UTC, tsurutan requested changes
確認お願いします！

2019-12-15 14:52 UTC, tsurutan commented on app/assets/javascripts/login.coffee
> +# Place all the behaviors and hooks related to the matching controller here.
こちらのファイルは不要なので消しましょう！

2019-12-15 14:52 UTC, tsurutan commented on app/assets/stylesheets/login.css
> +@charset "UTF-8";
こちら cssではなく sassを使用したほうがコード数が少なくかけるのでこちらを入れてみましょう！
またcssなのですが、スコープがグローバルなため命名規則に気をつけなくてはいけません。
この場合BEM記法というものがあるので、こちらを適用してみましょう！

2019-12-15 14:52 UTC, tsurutan commented on app/views/login/login.html.erb
> +<html lang="ja">
こちらhtmlではなくhamlを使用することでコード数を減らすことができるので、hamlを使いましょう！

2020-02-12 14:04 UTC, tsurutan requested changes
確認お願いします！

2020-02-12 14:04 UTC, tsurutan commented on app/views/login/login.html.haml
> +      %h1.login__title ログイン
文字は国際化に対応できるようにi18nを使用しましょう！
https://railsguides.jp/i18n.html

2020-02-12 14:04 UTC, tsurutan commented on config/routes.rb
> +  get 'login/login'
localhost:3000/login/login のように `login` が二回並び冗長になるのでこちらを localhost:3000/loginになるように変更しましょう。
またこちらのアクションが LoginController内の login関数に宣言されていますが、railsではこのようなログイン処理はSessionsControllerのnew関数に値するのでこちらに変更すると後々開発しやすくなるかと思います！

2020-02-25 15:16 UTC, tanakafumiaki commented on config/routes.rb
> +  get 'login/login'
ご指摘ありがとうございます。修正いたしました。

2020-03-24 22:11 UTC, tsurutan commented on app/assets/stylesheets/sessions.scss
> +  font: 15px/24px sans-serif;
font-sizeやmarginなど画面の大きさで調整したいものは `rem` を使用しましょう！
https://qiita.com/butchi_y/items/453654828d9d6c9f94b0

2020-03-24 22:14 UTC, tsurutan commented on app/assets/stylesheets/sessions.scss
> +  border: 1px solid #1b2538;
`#1b2538` のように、よく使用する色に関しては `app/assets/stylesheets/colors.scss` に
```scss
$font-color: #1b2538;
```

のように定義し、それを `import` し再利用する形を取るとメンテナンスしやすくなると思います！

2020-03-24 22:14 UTC, tsurutan commented on app/assets/stylesheets/sessions.scss
> +  font: 15px/24px sans-serif;
ただし `border-radius` や `border-width` などは、画面サイズが変わっても普遍だと思うのでこちらは変更しなくて大丈夫です！

2020-04-06 23:45 UTC, tsurutan approved these changes
LGTM!!

2020-04-16 22:23 UTC, merged